title: Halloween
description: 
author:
  name: 
permalink: /:title/
paginate: 5
paginate_path: /page:num/
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
